import _ from 'lodash'

const MAP = {
  INITIATED: 'INITIATED',
  IN_PROGRESS: 'IN_PROGRESS',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  // PAYMENT_PENDING: 'PAYMENT_PENDING',
  // PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  CANCELLED: 'CANCELLED'
}

const ENUM = _.values(MAP)

const DEFAULT = MAP.INITIATED

const TRIP_STATUS = {
  MAP,
  ENUM,
  DEFAULT
}

export default TRIP_STATUS
